[package]
name = "roxmltree-app"
version = "0.1.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
edition = "2018"

[workspace]

[[bin]]
name = "app"
path = "app.rs"

[dependencies]
roxmltree = { path = "../../" }
