[package]
name = "roxmltree"
# When updating version, also modify html_root_url in the lib.rs and in the README.md
version = "0.1.0"
authors = ["RazrFalcon <razrfalcon@gmail.com>"]
keywords = ["xml", "parser", "tree", "dom"]
categories = ["parsing"]
license = "MIT/Apache-2.0"
description = "Represent an XML as a read-only tree."
repository = "https://github.com/RazrFalcon/roxmltree"
documentation = "https://docs.rs/roxmltree/"
readme = "README.md"

[workspace]
members = ["benches"]
exclude = ["testing-tools"]

[dependencies]
#xmlparser = "0.6.0"
xmlparser = { git = "https://github.com/RazrFalcon/xmlparser.git", rev = "8a075b2" }
#xmlparser = { path = "../xmlparser" }

[dev-dependencies]
pretty_assertions = "0.5.1"
rustc-test = "0.3"
