[package]
name = "roxmltree"
# When updating version, also modify html_root_url in the lib.rs
version = "0.2.0"
authors = ["RazrFalcon <razrfalcon@gmail.com>"]
keywords = ["xml", "parser", "tree", "dom"]
categories = ["parsing"]
license = "MIT/Apache-2.0"
description = "Represent an XML as a read-only tree."
repository = "https://github.com/RazrFalcon/roxmltree"
documentation = "https://docs.rs/roxmltree/"
readme = "README.md"

[workspace]
members = ["benches"]
exclude = ["testing-tools"]

[lib]
doctest = true

[dependencies]
xmlparser = "0.6.1"

[dev-dependencies]
pretty_assertions = "0.5.1"
rustc-test = "0.3"
